project:
  type: website
  output-dir: docs

website:
  title: "Amanda Hammers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/amanda-hammers-068bbb250
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/amandahammers/amandahammers.github.io
          - text: Report a Bug
            href: https://github.com  

format:
  html:
    theme: minty  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

