project:
  type: website
  output-dir: docs

website:
  title: "Amanda Hammers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/amanda-hammers-068bbb250/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/amandahammers/amandahammers.github.io

format:
  html:
    theme: minty  
    css: styles.css
    toc: true
    mainfont: Palatino, URW Palladio L, serif

execute: 
  freeze: auto

